<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>reg</string>
			<string>REG</string>
		</array>
		<key>name</key>
		<string>Registry</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>Windows Registry Editor Version 5\.00|REGEDIT4</string>
				<key>name</key>
				<string>keyword.control.import.reg</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.reg</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(;).*$</string>
				<key>name</key>
				<string>comment.line.semicolon.reg</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b[\h]+\b</string>
				<key>name</key>
				<string>constant.numeric.hexadecimal.reg</string>
			</dict>

			<dict>
				<key>match</key>
				<string>,+</string>
				<key>name</key>
				<string>constant.numeric.hex.comma.reg</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\\</string>
				<key>name</key>
				<string>keyword.operator.arithmetic.linecontinuation.reg</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.section.reg</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.section.reg</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.section.reg</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s*(\[(?!-))(.*?)(\])</string>
				<key>name</key>
				<string>entity.name.function.section.add.reg</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.section.reg</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.section.reg</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.section.reg</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s*(\[-)(.*?)(\])</string>
				<key>name</key>
				<string>entity.name.function.section.delete.reg</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>support.constant.reg</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s?(@|["'].*?["'])\s*</string>
				<key>name</key>
				<string>meta.declaration.reg</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\s*=\s*</string>
				<key>name</key>
				<string>keyword.operator.reg</string>
			</dict>

			<dict>
				<key>match</key>
				<string>-</string>
				<key>name</key>
				<string>keyword.operator.reg</string>
			</dict>

			<dict>
				<key>match</key>
				<string>["'].*["']</string>
				<key>name</key>
				<string>string.quoted.reg</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>variable.parameter.datatype.reg</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.operator.brackets.reg</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>support.constant.reg</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>support.constant.reg</string>
					</dict>
				</dict>
				<key>match</key>
				<string>((?i:dword)|(?i:hex))(\(([\dabcdefABCDEF]*)\))?(\:)?</string>
				<key>name</key>
				<string>meta.declaration.reg</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.reg</string>
		<key>uuid</key>
		<string>B7773F5B-C43A-4BB9-843A-4AC119250EBD</string>
	</dict>
</plist>
